{% set name = "diot" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/diot-{{ version }}.tar.gz
  sha256: a8adc50e2d8e2a1d03ed017ecae98eb09a7ebb3bd0a5fbd44cbfb222e5a71bb4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.6
  run:
    - inflection <1.0.0
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - diot
  commands:
    - python -m pip check

about:
  home: https://github.com/pwwang/diot
  dev_url: https://github.com/pwwang/diot.git
  doc_url: https://pwwang.github.io/diot/
  summary: Python dictionary with dot notation
  license: MIT
  license_file: LICENSE
  description: |
    Python dictionary with dot notation (A re-implementation of
    python-box with some issues fixed and simplified)

extra:
  recipe-maintainers:
    - duncanmmacleod
